image: miadmin_android29:latest


build:
    script:
     - cd exercise_2/code
lintDebug:
  stage: build
  script:
    - cd exercise_2/code
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - cd exercise_2/code
    - ./gradlew assembleDebug
  artifacts:
    paths:
debugTests:
  stage: test
  script:
    - cd exercise_2/code
    - ./gradlew -Pci --console=plain :app:testDebug
